### ISSUE TITLE
Adding clarity to licensing

### ISSUE THREAD

**Issue by amazingrando** [isaaclyman/ttrpg-guide#6] opened 2024-03-21 21:51 UTC
**What's your idea?**

Licensing for RPGs has a lot of factors. For example, is a game licensed using the OGL, a Creative Commons license, or the ORC license?

Also how much of the game is licensed? Fate and Pathfinder have everything under their licenses, while D&D only licenses a little for 5e. 

**Why is this important to you?**

The nuance of licensing impacts what the community and individuals can do with it.

**Comment by isaaclyman** [comment] 2024-03-21 22:05
Duplicate of #2.

**Closed by isaaclyman** 2024-03-21 22:05 UTC
Labels: duplicate, feature request

**Comment by isaaclyman** [comment] 2024-03-22 18:45
The License column now includes more detailed information.
